### ISSUE TITLE
[Bug] - Changes List Tooltip being cutoff

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#188] opened 2022-09-09 00:50 UTC
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

production

### Observed Behavior

When the text for a change in the changes list is too long, the tooltip which shows up to the right when you hover over a change is cutoff.

### Expected Behavior

I imagine there should be open space to the right of all changes the size of the tooltip, so that it always has room to render. That or have the tooltip render above or below the change if it's being cutoff.

### Steps to Reproduce

1. Go to work package view page
2. Pick a change with text going almost to the right border of the box
3. Hover over the change and the tooltip to the right should be cutoff

### Screenshots (as needed)

![image](https://user-images.githubusercontent.com/29521172/189249878-f6e5b207-23fb-4c56-a657-9b4f08c386a7.png)

**Comment by anthonybernardi** [comment] 2022-09-09 01:05
duplicate of https://github.com/Northeastern-Electric-Racing/FinishLine/issues/64

**Closed by anthonybernardi** 2022-09-09 01:05 UTC
Labels: bug, front-end, straightforward
