### ISSUE TITLE
[Frontend] - Update ExternalLink Components to work with MUI icons

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/FinishLine#502] opened 2022-12-21 00:35 UTC
### Description

Right now the ExternalLink component is built to support the FontAwesomeIcons; however, since we've switched to MUI we have all these lovely new icons we should use, we should switch it to support these icons instead. 

### Acceptance Criteria

The ExternalLink component supports mui icons instead of fontAwesome icons

### Proposed Solution

This will involve changing the icon prop on the externalLink to be a ReactNode, changing the implementation in the externalLink file to render this new prop, and then updating everywhere externalLink is called to use MUI icons instead of fontAwesome icons. This ticket is marked medium because of how many places externalLink is used with an icon, so it might be kind of tedious

**Comment by anthonybernardi** [comment] 2023-02-04 23:12
duplicate of #814

**Closed by anthonybernardi** 2023-02-04 23:12 UTC
Labels: technical improvement, medium, front-end
